In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report)

from sklearn_nominal import ZeroRClassifier
from sklearn_nominal import OneRClassifier
from sklearn_nominal import PRISMClassifier
from sklearn_nominal import CN2Classifier

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
PATH='https://weblidi.info.unlp.edu.ar/catedras/MD_SI/DATOS/'
df = pd.read_csv(PATH + 'Drug5.csv')
#df = pd.read_csv('Drug5_atipicos.csv')
df.head()

X = df.drop('Drug', axis=1)
y = df['Drug']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na           200 non-null    float64
 5   K            200 non-null    float64
 6   Drug         200 non-null    object 
dtypes: float64(2), int64(1), object(4)
memory usage: 11.1+ KB


In [5]:
def validacion(y, y_pred):
    print("\nMETRICAS")
    print("-"*20)

    # Accuracy
    score = accuracy_score(y, y_pred)
    print(f"accuracy : {score:.2f}")

    # Matriz de Confusión
    cm = confusion_matrix(y, y_pred)
    print("\nMatriz de confusión")
    print(cm)

    # Métricas de Clasificación
    print('\nReporte de Clasificación:')
    print(classification_report(y, y_pred))

In [6]:
#-- Atributos nominales y numéricos ---
print(X.head())

model = OneRClassifier(criterion="accuracy")
model.fit(X, y)

y_pred = model.predict(X)

print("\nREGLAS - OneR")
print("-"*20)
print(model.pretty_print(np.unique(y)))

validacion(y, y_pred)

   Age Sex      BP Cholesterol        Na         K
0   23   F    HIGH        HIGH  0.792535  0.031258
1   47   M     LOW        HIGH  0.739309  0.056468
2   47   M     LOW        HIGH  0.697269  0.068944
3   28   F  NORMAL        HIGH  0.563682  0.072289
4   61   F     LOW        HIGH  0.559294  0.030998



REGLAS - OneR
--------------------
K <= 0.05415   => drugY
K > 0.05415    => drugX
Default: [0.115 0.08  0.08  0.27  0.455]

METRICAS
--------------------
accuracy : 0.65

Matriz de confusión
[[ 0  0  0 17  6]
 [ 0  0  0 15  1]
 [ 0  0  0 13  3]
 [ 0  0  0 40 14]
 [ 0  0  0  2 89]]

Reporte de Clasificación:
              precision    recall  f1-score   support

       drugA       0.00      0.00      0.00        23
       drugB       0.00      0.00      0.00        16
       drugC       0.00      0.00      0.00        16
       drugX       0.46      0.74      0.57        54
       drugY       0.79      0.98      0.87        91

    accuracy                           0.65       200
   macro avg       0.25      0.34      0.29       200
weighted avg       0.48      0.65      0.55       200



In [8]:
#-- Atributos numéricos --
X_num = pd.get_dummies(X)
print(X_num.head())

model = OneRClassifier()
model.fit(X_num, y)

y_pred = model.predict(X_num)

print("\nREGLAS - OneR")
print("-"*20)
print(model.pretty_print(np.unique(y)))

validacion(y, y_pred)

   Age        Na         K  Sex_F  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  \
0   23  0.792535  0.031258   True  False     True   False      False   
1   47  0.739309  0.056468  False   True    False    True      False   
2   47  0.697269  0.068944  False   True    False    True      False   
3   28  0.563682  0.072289   True  False    False   False       True   
4   61  0.559294  0.030998   True  False    False    True      False   

   Cholesterol_HIGH  Cholesterol_NORMAL  
0              True               False  
1              True               False  
2              True               False  
3              True               False  
4              True               False  

REGLAS - OneR
--------------------
K <= 0.05522   => drugY
K > 0.05522    => drugX
Default: [0.115 0.08  0.08  0.27  0.455]

METRICAS
--------------------
accuracy : 0.65

Matriz de confusión
[[ 0  0  0 17  6]
 [ 0  0  0 15  1]
 [ 0  0  0 13  3]
 [ 0  0  0 39 15]
 [ 0  0  0  1 90]]

Reporte de Clasificación:
    